labels:
  - "eagle"
server:
  host: "127.0.0.1"
  port: "9999"

etcd:
  endpoints:
    - "127.0.0.1:2380"
  prefix: "eagle"

docker:
  network: "bridge"

health:
  timeout: 5
  interval: 3
  checker:
    type: tcp

